spring:
  application:
    name: FitToServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/spring1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: qo0ZNtzizpcWq/E+Ou/FN8rcYDaycVNolSpOYhIPOOM=

  kakao:
    client-id: aaaaa
    redirect-uri: aaaaa
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

hashid:
  salt: fitto

springdoc:
  show-login-endpoint: true

logging:
  level:
    org.springframework.data.redis: DEBUG